name=LilyGO T-Glass-V3
version=1.0.0
author=LilyGo
maintainer=LewisHe <lewishe@outlook.com>
sentence=Library for LilyGO T-Glass-V3
paragraph=LilyGO AMOLED 1.02 Inch display product
category=Device Control
url=https://github.com/Xinyuan-LilyGO/T-Glass-V3
architectures=esp32
depends=lvgl, SensorLib, XPowersLib, RadioLib, ESP8266Audio, ESP8266SAM
