; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;!===============================VARIANT========================================
default_envs = T-Glass

;! ===============================Examples=======================================
;! The src_dir variable can only have one row

; src_dir = examples/BatteryVoltage
; src_dir = examples/CameraWebServer
; src_dir = examples/DeepSleep
src_dir = examples/Factory
; src_dir = examples/HelloWorld
; src_dir = examples/RecordWAV
; src_dir = examples/SX126x_PingPong
; src_dir = examples/SX126x_Receive_Interrupt
; src_dir = examples/SX126x_Transmit_Interrupt
; src_dir = examples/SimplePlayback
; src_dir = examples/SimplePlaybackWithTouch
; src_dir = examples/TouchButton

;! Don't make changes
boards_dir = boards

[env]
lib_extra_dirs = ${PROJECT_DIR} 
platform = espressif32@6.13.0
framework = arduino
upload_speed =  921600
monitor_speed = 115200
build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    ; Enable -DARDUINO_USB_CDC_ON_BOOT will start printing and wait for terminal access during startup
    -DARDUINO_USB_CDC_ON_BOOT=1

    ; Enable -UARDUINO_USB_CDC_ON_BOOT will turn off printing and will not block when using the battery
    ; -UARDUINO_USB_CDC_ON_BOOT

    -DCORE_DEBUG_LEVEL=4

board_build.partitions = huge_app.csv 


monitor_filters =
	default
	esp32_exception_decoder

lib_deps = 
    lvgl/lvgl @ ^8.4.0
    lewisxhe/SensorLib @ ^0.3.3
    lewisxhe/XPowersLib @ ^0.3.2
    FS
    SPIFFS
    SD
    jgromes/RadioLib @ ^7.7.1
    https://github.com/pschatzmann/arduino-audio-driver/archive/v0.2.0.zip
    earlephilhower/ESP8266Audio@1.9.9
    earlephilhower/ESP8266SAM@1.1.0

[env:T-Glass]
extends = env
board = T-Glass-V3
build_flags =
    ${env.build_flags}
board_build.filesystem = spiffs
board_build.partitions = huge_app.csv

