#pragma once

#include <cstddef>

#include "AstraSettings.h"

namespace astra_language {

enum class TextId : std::size_t {
    Home,
    Camera,
    Audio,
    Radio,
    LoRa,
    Network,
    Games,
    Device,
    CameraStatus,
    Gesture3D,
    GestureControl,
    CameraStream,
    MicrophoneVolume,
    SpeakerTest,
    InputTest,
    SendTest,
    ContinuousTransmit,
    ReceiveMonitor,
    LoRaParameters,
    WirelessStatus,
    WifiStatus,
    WifiScan,
    TimeNtp,
    DinoJump,
    Battery,
    Screen,
    Voltage,
    Charge,
    DisplayCalibration,
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    Save,
    Brightness,
    Settings,
    Wifi,
    GestureRecognition,
    Sleep,
    Shutdown,
    FactoryDiagnostics,
    LanguageMenu,
    Chinese,
    English,
    LanguageSelectedChinese,
    LanguageSelectedEnglish,
    CameraOnline,
    CameraOffline,
    FormatJpeg,
    FrameQvga,
    ShowGesture1To5,
    EnableGestureFirst,
    GestureOnePrevious,
    GestureTwoNext,
    GestureThreeOpen,
    GestureFourClose,
    GestureFivePlayback,
    WifiDisabled,
    EnableWifiFirst,
    WifiConnecting,
    WifiConnected,
    Ssid,
    Web,
    Stream,
    ServerOnline,
    ServerStarting,
    MicrophoneReady,
    MicrophoneOffline,
    BootPressed,
    BootIdle,
    TouchPressed,
    TouchIdle,
    Gpio0Gpio1,
    RadioOffline,
    RadioListening,
    RadioStopped,
    RadioReady,
    RadioStandby,
    ModeReceive,
    NoNetworks,
    CameraOk,
    CameraFail,
    MicActive,
    MicIdle,
    LoRaOk,
    LoRaFail,
    WifiOffline,
    RadioTitle,
    RadioWaitingForWifi,
    RadioConnecting,
    RadioBuffering,
    RadioPlaying,
    RadioPaused,
    RadioRetrying,
    RadioError,
    RadioIdle,
    WifiEnabledAction,
    WifiDisabledAction,
    GestureEnabledAction,
    GestureDisabledAction,
    SpeakerTestDone,
    LoRaOfflineAction,
    LoRaConfigError,
    LoRaSent,
    LoRaSendError,
    LoRaTransmitActive,
    LoRaTransmitStopped,
    DisplayMoved,
    DisplaySaved,
    BrightnessSet,
    Sleeping,
    ShutdownBlockedUsb,
    RadioStationError,
    Count,
};

struct TextPair {
    const char *chinese;
    const char *english;
};

inline constexpr TextPair kTextTable[] = {
    {"Astra 首页", "Astra Home"},
    {"相机", "Camera"},
    {"音频", "Audio"},
    {"网络电台", "Internet Radio"},
    {"LoRa", "LoRa"},
    {"网络", "Network"},
    {"游戏", "Games"},
    {"设备", "Device"},
    {"摄像头状态", "Camera Status"},
    {"3D 手势识别", "3D Gesture"},
    {"手势控制", "Gesture Control"},
    {"图传推流", "Camera Stream"},
    {"麦克风音量", "Microphone"},
    {"扬声器测试", "Speaker Test"},
    {"输入按键测试", "Input Test"},
    {"发送测试", "Send Test"},
    {"连续发送", "Continuous Transmit"},
    {"接收监视", "Receive Monitor"},
    {"LoRa 参数", "LoRa Parameters"},
    {"无线状态", "Wireless Status"},
    {"WiFi 状态", "WiFi Status"},
    {"WiFi 扫描", "WiFi Scan"},
    {"时间与 NTP", "Time & NTP"},
    {"恐龙跳一跳", "Dino Jump"},
    {"电池", "Battery"},
    {"屏幕", "Screen"},
    {"电压: ", "Voltage: "},
    {"电量: ", "Charge: "},
    {"屏幕校准", "Display Calibration"},
    {"上移", "Move Up"},
    {"下移", "Move Down"},
    {"左移", "Move Left"},
    {"右移", "Move Right"},
    {"保存", "Save"},
    {"亮度", "Brightness"},
    {"设置", "Settings"},
    {"WiFi", "WiFi"},
    {"手势识别", "Gesture Recognition"},
    {"休眠", "Sleep"},
    {"关机", "Power Off"},
    {"工厂诊断", "Factory Diagnostics"},
    {"语言", "Language"},
    {"中文", "Chinese"},
    {"English", "English"},
    {"已切换为中文", "Language: Chinese"},
    {"已切换为英文", "Language: English"},
    {"相机: 在线", "Camera: online"},
    {"相机: 离线", "Camera: offline"},
    {"格式: JPEG", "Format: JPEG"},
    {"帧: QVGA 320x240", "Frame: QVGA 320x240"},
    {"请显示手势 1-5", "Show gesture 1-5"},
    {"请到设置开启手势识别", "Open Settings: Gesture"},
    {"1: 上一项", "1: Previous"},
    {"2: 下一项", "2: Next"},
    {"3: 确认", "3: Open"},
    {"4: 返回", "4: Back"},
    {"5: 播放/暂停", "5: Play/Pause"},
    {"WiFi: 已关闭", "WiFi: disabled"},
    {"请先开启 WiFi", "Enable WiFi first"},
    {"WiFi: 连接中", "WiFi: connecting"},
    {"WiFi: 已连接", "WiFi: connected"},
    {"SSID: ", "SSID: "},
    {"网页: http://", "WEB: http://"},
    {"推流: :81/stream", "STREAM: :81/stream"},
    {"服务器: 在线", "Server: online"},
    {"服务器: 启动中", "Server: starting"},
    {"输入: 就绪", "Input: ready"},
    {"输入: 离线", "Input: offline"},
    {"BOOT: 按下", "BOOT: pressed"},
    {"BOOT: 空闲", "BOOT: idle"},
    {"TOUCH: 按下", "TOUCH: pressed"},
    {"TOUCH: 空闲", "TOUCH: idle"},
    {"GPIO0 / GPIO1", "GPIO0 / GPIO1"},
    {"无线电: 离线", "Radio: offline"},
    {"无线电: 接收中", "Radio: listening"},
    {"无线电: 已停止", "Radio: stopped"},
    {"SX1262: 就绪", "SX1262: ready"},
    {"模式: 待机", "Mode: standby"},
    {"模式: 接收", "Mode: receive"},
    {"没有找到网络", "No networks"},
    {"相机: 正常", "Camera: OK"},
    {"相机: 失败", "Camera: FAIL"},
    {"麦克风: 工作中", "Mic: active"},
    {"麦克风: 空闲", "Mic: idle"},
    {"LoRa: 正常", "LoRa: OK"},
    {"LoRa: 失败", "LoRa: FAIL"},
    {"WiFi: 离线", "WiFi: offline"},
    {"电台", "Radio"},
    {"等待网络", "Waiting for WiFi"},
    {"连接中", "Connecting"},
    {"缓冲中", "Buffering"},
    {"播放中", "Playing"},
    {"已暂停", "Paused"},
    {"重连中", "Retrying"},
    {"播放错误", "Playback error"},
    {"未播放", "Idle"},
    {"WiFi 已开启", "WiFi enabled"},
    {"WiFi 已关闭", "WiFi disabled"},
    {"手势识别已开启", "Gesture enabled"},
    {"手势识别已关闭", "Gesture disabled"},
    {"扬声器测试完成", "Speaker test"},
    {"LoRa 离线", "LoRa offline"},
    {"LoRa 配置错误", "LoRa config error"},
    {"LoRa 已发送", "LoRa sent"},
    {"LoRa 发送错误", "LoRa send error"},
    {"LoRa 连续发送中", "LoRa transmitting"},
    {"LoRa 已停止", "LoRa stopped"},
    {"屏幕已移动", "Display moved"},
    {"屏幕设置已保存", "Display saved"},
    {"亮度已设置", "Brightness set"},
    {"正在休眠", "Sleeping"},
    {"请拔出 USB", "Unplug USB"},
    {"电台选择错误", "Radio station error"},
};

static_assert(static_cast<std::size_t>(TextId::Count) ==
                  sizeof(kTextTable) / sizeof(kTextTable[0]),
              "Astra language table and TextId are out of sync");

inline const char *text(TextId id, astra_settings::Language language) {
    const std::size_t index = static_cast<std::size_t>(id);
    if (index >= sizeof(kTextTable) / sizeof(kTextTable[0])) return "";
    return language == astra_settings::Language::English ? kTextTable[index].english
                                                          : kTextTable[index].chinese;
}

} // namespace astra_language
